var lightDarkCount = 0;

function lightOrDark(){
    lightDarkCount++;
    if(lightDarkCount%2==0){
        $("body").css("background-color","white");
        $("body").css("color","black");
        $(".code").css("background","black");
        $(".code").css("color","white");
        $(".inline-code").css("background","black");
        $(".inline-code").css("color","white");
        $("#darkLight").addClass("btn-dark");
        $("#darkLight").removeClass("btn-light");
        $(".list-group-item").css("color","black");
        $(".comment").css("color","#80FF00");
        $(".var-name").css("color","#c0c0c0");
    }
    else if(lightDarkCount%2==1)
    {        
        $("body").css("background-color","black");
        $("body").css("color","white");
        $(".code").css("background","white");
        $(".code").css("color","black");
        $(".inline-code").css("background","white");
        $(".inline-code").css("color","black");
        $("#darkLight").addClass("btn-light");
        $("#darkLight").removeClass("btn-dark");
        $(".list-group-item").css("color","black");
        $(".comment").css("color","#0E4D92");
        $(".var-name").css("color","rgb(0,0,255)");
    }
}

$(document).ready(function(){
     $("#menu").click(function(){
         $("#menu-links").toggle();
     });    

    //Initially only comment thumbnail would be active & content of comment will be shown
    $("#item-com").addClass("active");
    $("#inner-content-var").css("display","none");
    $("#inner-content-str").css("display","none");
    $("#inner-content-arr").css("display","none");
    $("#inner-content-arith").css("display","none");
    $("#inner-content-comp").css("display","none");
    $("#inner-content-cond").css("display","none");
    $("#inner-content-obj").css("display","none");
    $("#inner-content-loop").css("display","none");
    $("#inner-content-rand").css("display","none");
    $("#inner-content-pars").css("display","none");
    $("#inner-content-rec").css("display","none");
    
    //1
    //When comment is clicked
    $("#item-com").click(function(){
        $("#item-com").addClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","block");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","none");
    });

    //2
    //When variable is clicked
    $("#item-var").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").addClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","block");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","none");
    });

    //3
    //When string is clicked
    $("#item-str").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").addClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","block");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","none");
    });

    //4
    //When array is clicked
    $("#item-arr").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").addClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","block");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","none");
    });

    //5
    //When arith is clicked
    $("#item-arith").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").addClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","block");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","none");
    });

    //6
    //When comp is clicked
    $("#item-comp").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").addClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","block");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","none");
    });

    //7
    //When cond is clicked
    $("#item-cond").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").addClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","block");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","none");
    });

    //8
    //When obj is clicked
    $("#item-obj").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").addClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","block");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","none");
    });

    //9
    //When loop is clicked
    $("#item-loop").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").addClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","block");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","none");
    });

    //10
    //When rand is clicked
    $("#item-rand").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").addClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","block");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","none");
    });

    //11
    //When pars is clicked
    $("#item-pars").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").addClass("active");
        $("#item-rec").removeClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","block");
        $("#inner-content-rec").css("display","none");
    });

    //12
    //When rec is clicked
    $("#item-rec").click(function(){
        $("#item-com").removeClass("active");
        $("#item-var").removeClass("active");
        $("#item-str").removeClass("active");
        $("#item-arr").removeClass("active");
        $("#item-arith").removeClass("active");
        $("#item-comp").removeClass("active");
        $("#item-cond").removeClass("active");
        $("#item-obj").removeClass("active");
        $("#item-loop").removeClass("active");
        $("#item-rand").removeClass("active");
        $("#item-pars").removeClass("active");
        $("#item-rec").addClass("active");
        $("#inner-content-com").css("display","none");
        $("#inner-content-var").css("display","none");
        $("#inner-content-str").css("display","none");
        $("#inner-content-arr").css("display","none");
        $("#inner-content-arith").css("display","none");
        $("#inner-content-comp").css("display","none");
        $("#inner-content-cond").css("display","none");
        $("#inner-content-obj").css("display","none");
        $("#inner-content-loop").css("display","none");
        $("#inner-content-rand").css("display","none");
        $("#inner-content-pars").css("display","none");
        $("#inner-content-rec").css("display","block");
    });
});